# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
- repo: self

jobs:
- deployment: busybox
  pool:
    vmImage: ubuntu-latest
  environment: prod.default
  strategy: 
    runOnce:
      deploy:
        steps:
        - script: |
            echo "HERE'S OUR DIRECTORY STUFF"
            ls $(Build.SourcesDirectory)
        - task: KubernetesManifest@0
          displayName: Deploy to Kubernetes cluster
          inputs:
            action: deploy
            namespace: default
            manifests: '$(Build.SourcesDirectory)/pod.yml'