apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: 
    - sleep
    args: ["600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
